### ISSUE TITLE
Extention fails when using a Shiny Scaffold

### ISSUE THREAD

**Issue by FlippieCoetser** [meakbiyik/vscode-r-test-adapter#22]
When developing and testing a R-Package, this extension works great!

When developing and testing a Shiny App, this extension throws an error.  

![image](https://user-images.githubusercontent.com/3672126/201080137-bfda7aaa-f663-4b03-b0b9-8ab1f3fa2b66.png)

Running the same tests in R-Studio everything works just fine

![image](https://user-images.githubusercontent.com/3672126/201080667-bf8cde8c-3d8d-4f07-9264-f3e57082ed8b.png)

Running the same tests using CMD everything also works just fine

![image](https://user-images.githubusercontent.com/3672126/201080539-5eff0fe4-2160-49a5-b867-8b905b3e0f83.png)

Here is an overview of my directory structure for this particular project:  

![image](https://user-images.githubusercontent.com/3672126/201081170-b04d1f15-0e91-4d4c-b781-7da39104e220.png)  

Do I miss something basic here? Do you need to have a DESCRIPTION file at the project's root?

**Comment by meakbiyik** [comment]
@FlippieCoetser Thanks a lot for your detailed report! I imagine it is because I am using devtools for a finer management of test runs, and (maybe?) R studio is using testthat directly. On that note, I am guessing that your insight is correct, that is, you need DESCRIPTION (and maybe other R package files like LICENSE?) for devtools to recognize this as a package.

Can you try it out with those additional files and let me know if things still work? If so, I will have to close this issue as this is expected behavior, I remember trying to get around devtools requirement but failing because of some reasons, and frankly I do not have time to see if anything has changed :)

**Comment by FlippieCoetser** [comment]
@meakbiyik I added a DESCRIPTION file with an additional element below
```yml
Suggests:
    shiytest2,
Config/testthat/edition: 3
```
This solved the problem for me.

I now only use Visual Studio Code and your Extention for all my R Development. Thanks, Great Extention!!!

![image](https://user-images.githubusercontent.com/3672126/202858456-68a46452-f0a5-4cad-b2cd-d845605c2b84.png)
