### ISSUE TITLE
Make it easier to see if any of the tests failed

### ISSUE THREAD

**Issue by krlmlr** [meakbiyik/vscode-r-test-adapter#3]
Until we have https://github.com/hbenl/vscode-test-explorer/issues/194, maybe we could add an overarching category to the tree (=hierarchy level)? When the tree is collaped, only one node would be shown.

**Comment by meakbiyik** [comment]
Unfortunately the API as seen [here](https://github.com/hbenl/vscode-test-adapter-api) provides no way to add an attribute to a node (i.e. test) on the fly, nor having it in multiple locations. I will see if I can send "fake" tests to the main extension during the running phase without retiring the current ones (by possibly providing an empty `retire` attribute?) but I wouldn't count on this, since the adapters as this one are not supposed to play with the design of the main extension. Will let you know.

**Comment by krlmlr** [comment]
Thanks. https://github.com/krlmlr/vscode-test-explorer/commit/5e5d7bf9c4d90c90d23112b3562d6ae3d885c9de works for me, let's hope we can fix upstream. I can run a custom version for a while.
