### ISSUE TITLE
Asynchronous reporting of test results

### ISSUE THREAD

**Issue by krlmlr** [meakbiyik/vscode-r-test-adapter#4]
I'd like to see the success/failure status of each test as soon as it is available.

Could be achieved with a custom testthat reporter that writes ndjson. Happy to help with the testthat side.

**Comment by meakbiyik** [comment]
Hmm. I can imagine using `spawn` instead of `exec` for the Rscript process, connecting a stream splitter on new lines like [this one](https://github.com/samcday/node-stream-splitter). Or maybe directly connecting the `exec` pipe to the splitter? Not quite sure if that will work because of the buffering issues. Also, I imagine I would need to feed the reporter code every time a test runs.

This is not a quite small task and I am a bit busy, so if you have some custom small-sized reporter that spits all the necessary information (error, skip, fail info, tracebacks and so on), I can give it a go, or you can also pitch in as you like and we can see how it goes.

In any case, if you are okay with the status reporting per each test file (rather than each test), that is much more doable. Would that be sufficient, or are you exclusively looking for test-level asynchronicity?

**Comment by krlmlr** [comment]
For starters we could do a clean interface to testthat's reporting facility, the merging would happen at the testthat side. I'm not sure what reporting granularity we'll see from that, I suspect at least file-wise, I'm okay with that.

Format-wise, it looks like a result like in https://github.com/hbenl/vscode-test-adapter-api#running-the-tests would work best? You could pass this through more or less directly?

```
{ type: 'started', tests: ['suite1'] }
{ type: 'suite', suite: 'suite1', state: 'running' }
{ type: 'test', test: 'test1', state: 'running' }
{ type: 'test', test: 'test1', state: 'passed' }
{ type: 'suite', suite: 'suite1', state: 'completed' }
{ type: 'finished' }
```

I need to look up what states are supported, ideally we'd also have 'warning'.

The reporter code will probably need to live in a separate file and be sourced from there.

**Comment by meakbiyik** [comment]
@krlmlr I implemented file-level immediate reporting. Let me know if it works for you: test-level reporting seems like a big hassle for now so as long as there isn't any proper testthat reporter to perform this I do not plan to invest time into it.

**Comment by krlmlr** [comment]
Thanks. This does work, but appears to be much slower than before. Tests run serially on my system, for each test a new R process seems to be started?

I'll take a look into implementing a custom reporter. Could you please comment if the format works for you?

**Comment by meakbiyik** [comment]
@krlmlr yes, unfortunately so. Parallelization should be possible but it would be a hassle (as the main test adapter extension is explicit about having a single process, and running tests in threads is not a solution either as that would mess with the stdout), and the with improvement of the reporting side the slowdown seemed like an acceptable trade-off here.

I will check out the reporter, though I am swamped these days and such an update requires a lot of implementation (I hate `child_process.spawn`, it never works as expected in Windows). Thanks for pitching in!

**Comment by krlmlr** [comment]
Thanks for the heads-up! testthat does parallel execution out of the box, the reporter framework properly aligns the statuses.
