### ISSUE TITLE
multiple folders in workspace causes error

### ISSUE THREAD

**Issue by yonicd** [meakbiyik/vscode-r-test-adapter#5]
if I have two R package folders in the workspace then both packages are being loaded in prep for a test.

in my current project i have [slickr](https://github.com/yonicd/slickR/blob/master/DESCRIPTION) and [carbonate](https://github.com/yonicd/carbonate/blob/master/DESCRIPTION) folders in the current workspace.

<img width="452" alt="Screen Shot 2021-03-07 at 9 24 08 AM" src="https://user-images.githubusercontent.com/1755487/110243093-e6a52700-7f26-11eb-8762-ac7602b53b64.png">

When i run a test for slickr it is erroring out because carbonate is missing a dep

```bash
[2021-03-07 14:15:25.305] [INFO] Test run finished
[2021-03-07 14:16:07.304] [INFO] Running testthat tests ["test-div.R"]
[2021-03-07 14:16:08.742] [ERROR] Loading carbonate
Error: Dependency package(s) 'rtweet' not available.
Backtrace:
    x
 1. \-devtools::test_file("/Users/yonis/projects/slickR/tests/testthat/test-div.R")
 2.   \-devtools::test(filter = regex, ...)
 3.     \-devtools::load_all(pkg$path, quiet = TRUE, export_all = export_all)
 4.       \-pkgload::load_all(...)
 5.         \-pkgload:::load_imports(path)
 6.           \-pkgload:::abort_for_missing_packages(res, imports$package)
Warning message:
In (function (dep_name, dep_ver = "*")  :
  Dependency package 'rtweet' not available.
Execution halted

```

also in the extension GUI doesn't differentiate between the two folders

<img width="411" alt="Screen Shot 2021-03-07 at 9 22 25 AM" src="https://user-images.githubusercontent.com/1755487/110243041-ba89a600-7f26-11eb-95fd-6e41e525e44f.png">

**Comment by meakbiyik** [comment]
Hmm, I see the issue (multiple ones actually):
* I am currently assuming a single package in the root, as this simplifies things immensely. Therefore, you see no difference in the GUI.
* The run issue is caused because I am using `devtools::test_file` to run the code, and give the workspace directory as cwd. Then, devtools loads the package in the given directory and runs the tests. 

I think I can solve this, maybe after resolving #6. Until then, I would recommend (and I imagine both vscode and many of the extensions in it also assumes) opening package folders as the root.

**Comment by yonicd** [comment]
This extension uses json settings to determine which workspace folder to focus on, it may be of help. https://github.com/ManuelHentschel/VSCode-R-Debugger

**Comment by meakbiyik** [comment]
@yonicd the new version should support this, try it out and let me know if something does not work.
