### ISSUE TITLE
Parse errors for tests don't show in test explorer

### ISSUE THREAD

**Issue by krlmlr** [meakbiyik/vscode-r-test-adapter#9]
Can we use a separate icon for a test file that fails to parse?

**Comment by meakbiyik** [comment]
Hmm not sure what you mean. No way to add more icons since that's on the main extension's side and this one only uses its API. For the tests that parse with errors, and yet still run, the icon is different (i.e. Fail vs. Error difference). I would recommend using other R extensions for general syntax checks, such as https://github.com/Ikuyadeu/vscode-R and https://github.com/REditorSupport/vscode-r-lsp, I personally use them both together.

**Comment by meakbiyik** [comment]
Will close this one -feel free to reopen if you got more details to add.
